### ISSUE TITLE
控制台报错

### ISSUE THREAD

**Issue by yufengya0420** [bedrock-dev/trapdoor-ll#103]
### trapdoor版本

trapdoor-0.38.0-1.20.0.01-34ad47e

### LiteLoaderBDS版本

2.14.1

### BDS版本

1.20.0.

### 发生了什么?

![image](https://github.com/bedrock-dev/trapdoor-ll/assets/99462074/32360de4-dbe3-444f-b58f-af5492512c1b)

**Comment by hhhxiao** [comment]
https://github.com/bedrock-dev/trapdoor-ll/commit/6bdf052d6f1b83df461bae17ac1abcc859a74e0f
