### ISSUE TITLE
希望增加一个功能：显示实体的碰撞箱

### ISSUE THREAD

**Issue by yufengya0420** [bedrock-dev/trapdoor-ll#109]
### 您的建议是否与现存的某个问题相关?请描述问题?

希望增加一个功能：显示实体的碰撞箱

### 您认为还缺少什么?如何解决您的问题?

希望增加一个功能：显示实体的碰撞箱

**Comment by hhhxiao** [comment]
服务端做不了实时渲染，延迟和拖影很高。
