### ISSUE TITLE
/hud add chuck不显示区块边界

### ISSUE THREAD

**Issue by yufengya0420** [bedrock-dev/trapdoor-ll#115]
### trapdoor版本

trapdoor-ll-0.40.0-1.20.11.01 下载链接是：trapdoor-0.39.0-1.20.0.01-18ae2e0.zip上周

### LiteLoaderBDS版本

2.15.0

### BDS版本

1.20.13

### 发生了什么?

/hud add chuck不显示区块边界

**Comment by hhhxiao** [comment]
这个是因为新版的资源版不包含区块边界粒子了，不太好办，你就当它没用了就行
