### ISSUE TITLE
史莱姆区块可视化无效

### ISSUE THREAD

**Issue by yufengya0420** [bedrock-dev/trapdoor-ll#117]
### trapdoor版本

trapdoor-0.39.0-1.20.0.01-18ae2e0

### LiteLoaderBDS版本

2.15.0

### BDS版本

1.20.13

### 发生了什么?

/slime show true 无法显示史莱姆区块
trapdoor-0.39.0-1.20.0.01-18ae2e0这个版本可以使用在1.20.13，不知道为什么，可能是版本号没改，但是已经适配了1.20.13

**Comment by yufengya0420** [comment]
![image](https://github.com/bedrock-dev/trapdoor-ll/assets/99462074/4604c0ab-f284-44ad-8c26-6ad071778a64)

**Comment by yufengya0420** [comment]
10:33:30 INFO [Server] - Trapdoor [v0.39.0] (trapdoor-0.39.0-1.20.0.01-18ae2e0.dll) 
10:33:30 INFO [Server]   Useful mod for technical players

**Comment by yufengya0420** [comment]
有人吗？？？

**Comment by hhhxiao** [comment]
测试没问题，请查看wiki检查资源版是否安装正确
